// Decompiled with JetBrains decompiler
// Type: LFConnect.Form4
// Assembly: LeapPad Manager, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null

using System.ComponentModel;
using System.Drawing;
using System.Windows.Forms;

namespace LFConnect
{
  public class Form4 : Form
  {
    private IContainer components = (IContainer) null;
    private GroupBox groupBox1;
    private GroupBox groupBox2;
    private GroupBox groupBox3;
    private Label label2;
    private Label label1;
    private Label label4;
    private Label label3;
    private Label label6;
    private Label label5;
    private Label label7;
    private Label label8;
    private Label label10;
    private Label label9;
    private Label label13;
    private Label label12;
    private Label label11;
    private Label label16;
    private Label label15;
    private Label label14;

    public Form4() => this.InitializeComponent();

    protected override void Dispose(bool disposing)
    {
      if (disposing && this.components != null)
        this.components.Dispose();
      base.Dispose(disposing);
    }

    private void InitializeComponent()
    {
      ComponentResourceManager componentResourceManager = new ComponentResourceManager(typeof (Form4));
      this.groupBox1 = new GroupBox();
      this.label10 = new Label();
      this.label9 = new Label();
      this.label8 = new Label();
      this.label7 = new Label();
      this.label6 = new Label();
      this.label5 = new Label();
      this.label4 = new Label();
      this.label3 = new Label();
      this.label2 = new Label();
      this.label1 = new Label();
      this.groupBox2 = new GroupBox();
      this.label13 = new Label();
      this.label12 = new Label();
      this.label11 = new Label();
      this.groupBox3 = new GroupBox();
      this.label16 = new Label();
      this.label15 = new Label();
      this.label14 = new Label();
      this.groupBox1.SuspendLayout();
      this.groupBox2.SuspendLayout();
      this.groupBox3.SuspendLayout();
      this.SuspendLayout();
      this.groupBox1.Controls.Add((Control) this.label10);
      this.groupBox1.Controls.Add((Control) this.label9);
      this.groupBox1.Controls.Add((Control) this.label8);
      this.groupBox1.Controls.Add((Control) this.label7);
      this.groupBox1.Controls.Add((Control) this.label6);
      this.groupBox1.Controls.Add((Control) this.label5);
      this.groupBox1.Controls.Add((Control) this.label4);
      this.groupBox1.Controls.Add((Control) this.label3);
      this.groupBox1.Controls.Add((Control) this.label2);
      this.groupBox1.Controls.Add((Control) this.label1);
      this.groupBox1.Location = new Point(12, 12);
      this.groupBox1.Name = "groupBox1";
      this.groupBox1.Size = new Size(736, 355);
      this.groupBox1.TabIndex = 0;
      this.groupBox1.TabStop = false;
      this.groupBox1.Text = "Main Program";
      this.label10.AutoSize = true;
      this.label10.Font = new Font("Microsoft Sans Serif", 11.25f, FontStyle.Regular, GraphicsUnit.Point, (byte) 0);
      this.label10.Location = new Point(153, 34);
      this.label10.MaximumSize = new Size(600, 0);
      this.label10.Name = "label10";
      this.label10.Size = new Size(585, 54);
      this.label10.TabIndex = 60;
      this.label10.Text = "Plug in your device through USB and make sure the LFconnect software is not running.  On the menu choose LeapPad / Connect. You will most likely need administrator permissions";
      this.label9.AutoSize = true;
      this.label9.Font = new Font("Microsoft Sans Serif", 12f, FontStyle.Bold, GraphicsUnit.Point, (byte) 0);
      this.label9.Location = new Point(8, 33);
      this.label9.MaximumSize = new Size(400, 0);
      this.label9.Name = "label9";
      this.label9.Size = new Size(139, 20);
      this.label9.TabIndex = 59;
      this.label9.Text = "Getting Started:";
      this.label8.AutoSize = true;
      this.label8.Font = new Font("Microsoft Sans Serif", 11.25f, FontStyle.Regular, GraphicsUnit.Point, (byte) 0);
      this.label8.Location = new Point(153, 304);
      this.label8.MaximumSize = new Size(580, 0);
      this.label8.Name = "label8";
      this.label8.Size = new Size(572, 36);
      this.label8.TabIndex = 58;
      this.label8.Text = "This is only to be used if you know what you are doing. Simply enter a shell command you wish to run on the device and push the button to send it";
      this.label7.AutoSize = true;
      this.label7.Font = new Font("Microsoft Sans Serif", 12f, FontStyle.Bold, GraphicsUnit.Point, (byte) 0);
      this.label7.Location = new Point(8, 303);
      this.label7.MaximumSize = new Size(400, 0);
      this.label7.Name = "label7";
      this.label7.Size = new Size(141, 20);
      this.label7.TabIndex = 57;
      this.label7.Text = "Send Command:";
      this.label6.AutoSize = true;
      this.label6.Font = new Font("Microsoft Sans Serif", 11.25f, FontStyle.Regular, GraphicsUnit.Point, (byte) 0);
      this.label6.Location = new Point(153, 235);
      this.label6.MaximumSize = new Size(580, 0);
      this.label6.Name = "label6";
      this.label6.Size = new Size(564, 36);
      this.label6.TabIndex = 56;
      this.label6.Text = "This is only to be used if you know what you are doing. Simply put in the path to a file on the device you wish to download and push the download file button";
      this.label5.AutoSize = true;
      this.label5.Font = new Font("Microsoft Sans Serif", 12f, FontStyle.Bold, GraphicsUnit.Point, (byte) 0);
      this.label5.Location = new Point(8, 234);
      this.label5.MaximumSize = new Size(400, 0);
      this.label5.Name = "label5";
      this.label5.Size = new Size((int) sbyte.MaxValue, 20);
      this.label5.TabIndex = 55;
      this.label5.Text = "Download File:";
      this.label4.AutoSize = true;
      this.label4.Font = new Font("Microsoft Sans Serif", 11.25f, FontStyle.Regular, GraphicsUnit.Point, (byte) 0);
      this.label4.Location = new Point(153, 177);
      this.label4.MaximumSize = new Size(600, 0);
      this.label4.Name = "label4";
      this.label4.Size = new Size(453, 18);
      this.label4.TabIndex = 54;
      this.label4.Text = "Simply select the item you wish to delete and push the delete button.";
      this.label3.AutoSize = true;
      this.label3.Font = new Font("Microsoft Sans Serif", 12f, FontStyle.Bold, GraphicsUnit.Point, (byte) 0);
      this.label3.Location = new Point(8, 176);
      this.label3.MaximumSize = new Size(400, 0);
      this.label3.Name = "label3";
      this.label3.Size = new Size((int) sbyte.MaxValue, 20);
      this.label3.TabIndex = 53;
      this.label3.Text = "Deleting Apps:";
      this.label2.AutoSize = true;
      this.label2.Font = new Font("Microsoft Sans Serif", 11.25f, FontStyle.Regular, GraphicsUnit.Point, (byte) 0);
      this.label2.Location = new Point(153, 109);
      this.label2.MaximumSize = new Size(600, 0);
      this.label2.Name = "label2";
      this.label2.Size = new Size(562, 36);
      this.label2.TabIndex = 52;
      this.label2.Text = "Once you have created a theme or video, simply drag / drop it anywhere on the main program to install it.";
      this.label1.AutoSize = true;
      this.label1.Font = new Font("Microsoft Sans Serif", 12f, FontStyle.Bold, GraphicsUnit.Point, (byte) 0);
      this.label1.Location = new Point(8, 108);
      this.label1.MaximumSize = new Size(400, 0);
      this.label1.Name = "label1";
      this.label1.Size = new Size(133, 20);
      this.label1.TabIndex = 51;
      this.label1.Text = "Installing Apps:";
      this.groupBox2.Controls.Add((Control) this.label13);
      this.groupBox2.Controls.Add((Control) this.label12);
      this.groupBox2.Controls.Add((Control) this.label11);
      this.groupBox2.Location = new Point(12, 381);
      this.groupBox2.Name = "groupBox2";
      this.groupBox2.Size = new Size(366, 237);
      this.groupBox2.TabIndex = 1;
      this.groupBox2.TabStop = false;
      this.groupBox2.Text = "Theme Maker";
      this.label13.AutoSize = true;
      this.label13.Font = new Font("Microsoft Sans Serif", 11.25f, FontStyle.Regular, GraphicsUnit.Point, (byte) 0);
      this.label13.Location = new Point(9, 154);
      this.label13.MaximumSize = new Size(350, 0);
      this.label13.Name = "label13";
      this.label13.Size = new Size(326, 18);
      this.label13.TabIndex = 63;
      this.label13.Text = "Your themes will be located in the Themes folder";
      this.label12.AutoSize = true;
      this.label12.Font = new Font("Microsoft Sans Serif", 11.25f, FontStyle.Regular, GraphicsUnit.Point, (byte) 0);
      this.label12.Location = new Point(9, 95);
      this.label12.MaximumSize = new Size(350, 0);
      this.label12.Name = "label12";
      this.label12.Size = new Size(332, 36);
      this.label12.TabIndex = 62;
      this.label12.Text = "Once done, you can drag / drop the .tar file to the main program to install.";
      this.label11.AutoSize = true;
      this.label11.Font = new Font("Microsoft Sans Serif", 11.25f, FontStyle.Regular, GraphicsUnit.Point, (byte) 0);
      this.label11.Location = new Point(9, 26);
      this.label11.MaximumSize = new Size(350, 0);
      this.label11.Name = "label11";
      this.label11.Size = new Size(336, 54);
      this.label11.TabIndex = 61;
      this.label11.Text = "Drop up to 10 images you wish to use in your theme, choose the name and developer and push the Create Theme button. ";
      this.groupBox3.Controls.Add((Control) this.label16);
      this.groupBox3.Controls.Add((Control) this.label15);
      this.groupBox3.Controls.Add((Control) this.label14);
      this.groupBox3.Location = new Point(384, 381);
      this.groupBox3.Name = "groupBox3";
      this.groupBox3.Size = new Size(364, 237);
      this.groupBox3.TabIndex = 2;
      this.groupBox3.TabStop = false;
      this.groupBox3.Text = "Video Creator";
      this.label16.AutoSize = true;
      this.label16.Font = new Font("Microsoft Sans Serif", 11.25f, FontStyle.Regular, GraphicsUnit.Point, (byte) 0);
      this.label16.Location = new Point(6, 188);
      this.label16.MaximumSize = new Size(350, 0);
      this.label16.Name = "label16";
      this.label16.Size = new Size(332, 36);
      this.label16.TabIndex = 64;
      this.label16.Text = "Once done, you can drag / drop the .tar file to the main program to install.";
      this.label15.AutoSize = true;
      this.label15.Font = new Font("Microsoft Sans Serif", 11.25f, FontStyle.Regular, GraphicsUnit.Point, (byte) 0);
      this.label15.Location = new Point(6, 118);
      this.label15.MaximumSize = new Size(350, 0);
      this.label15.Name = "label15";
      this.label15.Size = new Size(350, 54);
      this.label15.TabIndex = 65;
      this.label15.Text = "You will then need to edit the icons to match what the video is. Once done, simply push the Create App button and your .tar file will be in the Videos folder";
      this.label14.AutoSize = true;
      this.label14.Font = new Font("Microsoft Sans Serif", 11.25f, FontStyle.Regular, GraphicsUnit.Point, (byte) 0);
      this.label14.Location = new Point(6, 25);
      this.label14.MaximumSize = new Size(350, 0);
      this.label14.Name = "label14";
      this.label14.Size = new Size(349, 72);
      this.label14.TabIndex = 64;
      this.label14.Text = componentResourceManager.GetString("label14.Text");
      this.AutoScaleDimensions = new SizeF(6f, 13f);
      this.AutoScaleMode = AutoScaleMode.Font;
      this.ClientSize = new Size(760, 628);
      this.Controls.Add((Control) this.groupBox3);
      this.Controls.Add((Control) this.groupBox2);
      this.Controls.Add((Control) this.groupBox1);
      this.Icon = (Icon) componentResourceManager.GetObject("$this.Icon");
      this.Name = nameof (Form4);
      this.StartPosition = FormStartPosition.CenterScreen;
      this.Text = "Help";
      this.groupBox1.ResumeLayout(false);
      this.groupBox1.PerformLayout();
      this.groupBox2.ResumeLayout(false);
      this.groupBox2.PerformLayout();
      this.groupBox3.ResumeLayout(false);
      this.groupBox3.PerformLayout();
      this.ResumeLayout(false);
    }
  }
}
